export const categoryMappings = {
  frozen: 'Frozen',
  'dairy-eggs': 'Dairy & Eggs',
  'fish-seafood': 'Fish & Seafood',
  beverages: 'Beverages',
  pantry: 'Pantry',
  'world-cuisine': 'World Cuisine',
  'meat-poultry': 'Meat & Poultry',
  'deli-prepared-meals': 'Deli & Prepared Meals',
  snacks: 'Snacks',
  'fruits-vegetables': 'Fruits & Vegetables',
  'organic-groceries': 'Organic Groceries',
  'bread-bakery-products': 'Bread & Bakery Products',
};

export const subcategoryMappings = {
  'sweet-snacks-candy': 'Sweet Snacks & Candy',
  'sports-energy-drinks': 'Sports & Energy Drinks',
  'deli-meats': 'Deli Meats',
  'fresh-pizza-pasta-sauces': 'Fresh Pizza, Pasta & Sauces',
  'ready-meals-sides': 'Ready Meals & Sides',
  pork: 'Pork',
  coffee: 'Coffee',
  'eggs-dairy-alternatives-product': 'Eggs & Dairy Alternatives',
  'fresh-cut-fruits-vegetables': 'Fresh Cut Fruits & Vegetables',
  'herbs-spices-sauces': 'Herbs, Spices & Sauces',
  'lamb-game-meat': 'Lamb & Game Meat',
  'drink-mixes': 'Drink Mixes',
  'sour-cream-dips': 'Sour Cream & Dips',
  eggs: 'Eggs',
  'packaged-bread': 'Packaged Bread',
  'sausages-bacon': 'Sausages & Bacon',
  'soft-drinks': 'Soft Drinks',
  'vegan-vegetarian-food': 'Vegan & Vegetarian Food',
  'deli-cheese': 'Deli Cheese',
  'cereals-spreads-syrups': 'Cereals, Spreads & Syrups',
  'meat-poultry': 'Meat & Poultry',
  'antipasto-dips-pates': 'Antipasto, Dips & Pates',
  'frozen-meat': 'Frozen Meat',
  'meats-poultry-ocean-products': 'Meats, Poultry & Ocean Products',
  pantry: 'Pantry',
  'chilled-desserts-dough': 'Chilled Desserts & Dough',
  sides: 'Sides',
  yogurt: 'Yogurt',
  'soy-rice-nut-beverages': 'Soy, Rice & Nut Beverages',
  'vegan-vegetarian': 'Vegan & Vegetarian',
  'pasta-rice-beans': 'Pasta, Rice & Beans',
  'iced-tea-coffee': 'Iced Tea & Coffee',
  'juices-drinks': 'Juices & Drinks',
  'packaged-cheese': 'Packaged Cheese',
  'dried-fruits-nuts': 'Dried Fruits & Nuts',
  'milk-cream-butter': 'Milk, Cream & Butter',
  'fruits-vegetables': 'Fruits & Vegetables',
  'fish-seafood': 'Fish & Seafood',
  'appetizers-snacks': 'Appetizers & Snacks',
  'baking-ingredients': 'Baking Ingredients',
  indian: 'Indian',
  'canned-jarred': 'Canned & Jarred',
  asian: 'Asian',
  'salty-snacks': 'Salty Snacks',
  'freshly-baked-bread-baguettes': 'Freshly Baked Bread & Baguettes',
  'oils-vinegars': 'Oils & Vinegars',
  'prepared-fish-seafood': 'Prepared Fish & Seafood',
  'tea-hot-drinks': 'Tea & Hot Drinks',
  vegetables: 'Vegetables',
  'packaged-salads-vegetables': 'Packaged Salads & Vegetables',
  'nuts-seeds-fruit': 'Nuts, Seeds & Fruit',
  'beef-veal': 'Beef & Veal',
  water: 'Water',
  'desserts-pastries': 'Desserts & Pastries',
  'buns-rolls': 'Buns & Rolls',
  'marinated-prepared-meat': 'Marinated & Prepared Meat',
  'chicken-turkey': 'Chicken & Turkey',
  'fresh-herbs': 'Fresh Herbs',
  'tortillas-flat-breads': 'Tortillas & Flat Breads',
  fruits: 'Fruits',
  'muffins-bagels-baked-goods': 'Muffins, Bagels & Baked Goods',
  'condiments-toppings': 'Condiments & Toppings',
};
